#!/bin/sh
MATCHES=$(mktemp /tmp/sentXXXXX)
STDIN=$(mktemp /tmp/sentXXXX)

CHAR="馑"
BACKTICKS='```'

MATCH="$CHAR[^$CHAR]*$CHAR"

mkdir -p code

sed "s/$BACKTICKS/$CHAR/g" | tr "\n" "\f" | tee $STDIN | grep -Eo "$MATCH" > $MATCHES

while read -r line; do
	HASH=$(echo $line | md5sum - | cut -d" " -f1)
	SYNTAX=$(echo "$line" | grep -o "$CHAR\w*" | cut -b 4-)

	CODELINES=$(echo $line | tr -dc "\f" | wc -c)
	FONTSIZE=$(expr 540 / $CODELINES)

	[ -e "code/$HASH.ff" ] || echo "$line" \
		| sed -E "s/$CHAR\w*\W(.*)\W$CHAR/\1/" \
		| tr "\f" "\n"  \
		| highlight -K $FONTSIZE -I -Osvg -S "$SYNTAX" - \
		| 2ff > code/$HASH.ff
	
	sed -Ei "s|$MATCH|@code/$HASH.ff|" $STDIN
done <$MATCHES 

<$STDIN tr "\f" "\n" | sed "s/$CHAR/$BACKTICKS/g"

rm "$MATCHES"
rm "$STDIN"
