#!/bin/sh
MATCHES=$(mktemp /tmp/sentXXXXX)
STDIN=$(mktemp /tmp/sentXXXX)

tr "\n" "\f" | tee $STDIN | grep -o '```[^`]*```' > $MATCHES

while read -r line; do
	HASH=$(echo $line | md5sum - | cut -d" " -f1)
	SYNTAX=$(echo "$line" | grep -o '```\w*' | cut -b 4-)
	echo "$line" \
		| sed -E 's/```\w*\f(.*)\f```/\1/' \
		| tr "\f" "\n"  \
		| highlight -K 20 --syntax $SYNTAX -I -Osvg - \
		| 2ff > /tmp/$HASH.ff
	
	MATCH='```[^`]*```'
	sed -i "s|$MATCH|@/tmp/$HASH.ff|" $STDIN
done <$MATCHES 

<$STDIN tr "\f" "\n"

rm "$MATCHES"
rm "$STDIN"
